name = "Wacha Minecraft"
author = "wacha-minecraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09c3a3f46ec7c1557cb806cfedd5bc915ad119853d375e9f938122f2dafa6008"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
