name = "Wacha Minecraft"
author = "wacha-minecraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38bb04905717faab166a3296a273c7c5e47dd42b03d3c4c763e2ba35789b65e"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
